Repository dogecoinfoundation/dogecoin.com, pull requests merged in 2022-08, with the labels that each got.

#151 Translation Portuguese from Portugal (partial)
  config.toml
  i18n/pt-pt.toml
Labels: help wanted, translation

#157 Enable Dogecoin Developers Dogepedia article
  content/de/dogepedia.md
  content/de/dogepedia/articles/dogecoin-developers.md
  content/en/dogepedia.md
  content/en/dogepedia/articles/dogecoin-developers.md
  content/es/dogepedia.md
  content/es/dogepedia/articles/dogecoin-developers.md
  content/fr/dogepedia.md
  content/fr/dogepedia/articles/dogecoin-developers.md
  content/kr/dogepedia.md
  content/kr/dogepedia/articles/dogecoin-developers.md
  content/no/dogepedia.md
  content/no/dogepedia/articles/dogecoin-developers.md
  content/pt-pt/dogepedia.md
  content/pt-pt/dogepedia/articles/dogecoin-developers.md
  content/th/dogepedia.md
  content/th/dogepedia/articles/dogecoin-developers.md
  content/zh-cn/dogepedia.md
  content/zh-cn/dogepedia/articles/dogecoin-developers.md
Labels: dogepedia

#125 Implement mobile changes
  themes/hello-friend-ng/assets/scss/_dogepedia.scss
  themes/hello-friend-ng/assets/scss/_menu.scss
  themes/hello-friend-ng/assets/scss/_prism.scss
  themes/hello-friend-ng/layouts/partials/community.html
Labels: ui-improvment

#158 Contributors fix
  content/de/contributors/Richard.md
  content/en/contributors/Richard.md
  content/es/contributors/Richard.md
  content/fr/contributors/Richard.md
  content/kr/contributors/Richard.md
  content/no/contributors/Richard.md
  content/pt-pt/contributors/Richard.md
  content/th/contributors/Richard.md
  content/zh-cn/contributors/Richard.md
Labels: documentation

#155 Fix header SEO
  themes/hello-friend-ng/layouts/partials/head.html
Labels: ui-improvment

#175 Fix Dogepedia Links #153
  themes/hello-friend-ng/assets/scss/_normalize.scss
Labels: ui-improvment

#190 Fix Ledger Wallet link https://github.com/dogecoinfoundation/dogecoin.com/issues/176
  content/de/wallets/Ledger.md
  content/en/wallets/Ledger.md
  content/es/wallets/Ledger.md
  content/fr/wallets/Ledger.md
  content/kr/wallets/Ledger.md
  content/no/wallets/Ledger.md
  content/pt-pt/wallets/Ledger.md
  content/th/wallets/Ledger.md
  content/zh-cn/wallets/Ledger.md
Labels: bug

#189 Dogecoin Core Wallet Upgrade llink
  themes/hello-friend-ng/layouts/index.html
Labels: ui-improvment

#191 Added Atomic Wallet
  content/de/wallets/AtomicWallet.md
  content/en/wallets/AtomicWallet.md
  content/es/wallets/AtomicWallet.md
  content/fr/wallets/AtomicWallet.md
  content/kr/wallets/AtomicWallet.md
  content/no/wallets/AtomicWallet.md
  content/pt-pt/wallets/AtomicWallet.md
  content/th/wallets/AtomicWallet.md
  content/zh-cn/wallets/AtomicWallet.md
Labels: ui-improvment

#187 translate several articles into Chinese
  config.toml
  content/zh-cn/dogepedia/articles/how-do-i-get-a-wallet.md
  content/zh-cn/dogepedia/faq/putting-a-cap-on-dogecoin.md
  content/zh-cn/resources.md
  i18n/zh-cn.toml
Labels: help wanted, translation

#192 AtomicWallet - Removed Opensource Tag
  content/de/wallets/AtomicWallet.md
  content/en/wallets/AtomicWallet.md
  content/es/wallets/AtomicWallet.md
  content/fr/wallets/AtomicWallet.md
  content/kr/wallets/AtomicWallet.md
  content/no/wallets/AtomicWallet.md
  content/pt-pt/wallets/AtomicWallet.md
  content/th/wallets/AtomicWallet.md
  content/zh-cn/wallets/AtomicWallet.md
Labels: ui-improvment

#188 CN trans
  content/zh-cn/dogepedia/articles/dogecoin-hardware-wallets.md
Labels: help wanted, translation
